edit movies_admin Makefile

diff --git a/movies_admin/Makefile b/movies_admin/Makefile
--- a/movies_admin/Makefile
+++ b/movies_admin/Makefile
@@ -1,51 +1,99 @@
+# Useful command to display all available Makefile commands with `make help`
 help:  ## Display this help
 	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
 	  | sort \
 	  | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[0;32m%-30s\033[0m %s\n", $$1, $$2}'
 
 #-----------------------------------------------------------------------------
-dotenv: ## Create .env file from template .env.example file
-	@test ! -f ./config/envs/.env && cp ./config/envs/.env.example ./config/envs/.env
-	@echo ".env file created succesfully. Don't forget to change credentials in it!"
+# Utility commands
 
-install: dotenv ## Create virtual env and install dependencies via poetry
+wheels:  # Build wheels with/without dev dependencies (used for building Docker containers)
+ifeq (${MODE}, dev)
+	pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements-dev.txt
+else ifeq ($(filter ${MODE}, prod),${MODE})
+	pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt
+else
+	@echo "Error: MODE env variable not set properly. Please set MODE to 'dev' or 'prod'."
+	@exit 1
+endif
+
+wait-postgres:  # Helper command to wait for postgres server or container to start up
+	python3 ./utils/wait_for_postgres.py
+
+
+
+#-----------------------------------------------------------------------------
+# Setting up the app
+
+install: ## Create venv and install app dependencies via poetry (to run app locally)
 	@poetry install --no-root
 
-start-dev-server: ## start django dev server
-	@poetry run python3 manage.py runserver
-
-migrate: ## apply django migrations
+migrate: ## Apply django migrations
 	@poetry run python3 manage.py migrate --fake movies 0001
 	@poetry run python3 manage.py migrate
 
-makemigrations: ## create new migrations if required
+migrate-docker: ## Apply django migrations (when running app in Docker)
+	@python3 manage.py migrate --fake movies 0001
+	@python3 manage.py migrate
+
+makemigrations: ## Create new migrations if required
 	@poetry run python3 manage.py makemigrations
 
-createsuperuser: ## create django superuser
+superuser: ## Create django superuser
 	@poetry run python3 manage.py createsuperuser
 
-createsuperuser-dev: ## autocreate test superuser with predefined login/pass
+superuser-docker: ## Create django superuser (when running app in Docker)
+	@python3 manage.py createsuperuser
+
+dummy-superuser: ## Autocreate test superuser with predefined login/pass
 	@DJANGO_SUPERUSER_USERNAME=admin \
 	DJANGO_SUPERUSER_PASSWORD=wow-so-secret \
 	DJANGO_SUPERUSER_EMAIL=mail@mail.kek \
 	poetry run python3 manage.py createsuperuser --noinput || true && \
 	echo "Test Django superuser login/pass: admin / wow-so-secret"
 
-translation: ## prepare files for translation
+dummy-superuser-docker: ## Autocreate test superuser (when running app in Docker)
+	@DJANGO_SUPERUSER_USERNAME=admin \
+	DJANGO_SUPERUSER_PASSWORD=wow-so-secret \
+	DJANGO_SUPERUSER_EMAIL=mail@mail.kek \
+	python3 manage.py createsuperuser --noinput || true && \
+	echo "Test Django superuser login/pass: admin / wow-so-secret"
+
+translation: ## Prepare files for translation
 	@poetry run django-admin makemessages -i "venv" -i ".venv" -l en -l ru
 
-compile-translation: ## compile translation
+compile-translation: ## Compile translation
 	@poetry run django-admin compilemessages -i "venv" -i ".venv" -l en -l ru
+
+#-----------------------------------------------------------------------------
+# Running the app server
+
+run-dev-server:	## Run django dev server
+	@poetry run python3 manage.py runserver
+
+run-dev-server-docker: \
+	wait-postgres \
+	migrate-docker	## Run django dev server (when running app in Docker)
+
+	@python3 manage.py runserver 0.0.0.0:8000
+
 
 
 #-----------------------------------------------------------------------------
 .PHONY: \
+	help \
+	wheels \
+	wait-postgres \
 	dotenv \
 	install \
-	start-dev-server \
 	migrate \
+	migrate-docker \
 	makemigrations \
-	createsuperuser \
-	createsuperuser-dev \
+	superuser \
+	superuser-docker \
+	dummy-superuser \
+	dummy-superuser-docker \
 	translation \
 	compile-translation \
+	run-dev-server \
+	run-dev-server-docker \
